name: sockboom及网易云签到

on:
  workflow_dispatch: # 手动触发
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: # 计划任务触发
    - cron: '0 16 * * *'
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天9点0分（9点整）
    # 建议每个人通过设置 GitHub Environments 的方式来设定为自己的目标运行时间（详细设置方法见文档说明）
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      # 检出
      - name: Checkout
        uses: actions/checkout@v2
      # 安装 Python
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
         
      - name: '安装 requirements'
        run: pip install -r ./requirements.txt 
        
      - name: 'Install dependencies'
        run: python -m pip install --upgrade DecryptLogin
      
      - name: '运行签到脚本'  
        run: python3 sockboom.py
        env:
            NETEASE_USERNAME: ${{ secrets.NETEASE_USERNAME }}
            NETEASE_PASSWORD: ${{ secrets.NETEASE_PASSWORD }}
            webhook : ${{ secrets.webhook  }}
            email: ${{ secrets.email }}
            passwd: ${{ secrets.passwd }}
            serverkey:  ${{ secrets.serverkey }} 
    
